### ISSUE TITLE
Find a place to host the large version of the mockflow image export

### ISSUE THREAD

**Issue by mireille-raad** [OC-Bandung/Documentation#3]
When we put the mockflow chart in a word document as part of the documentation, the size of the image becomes small and can not read well.

We need to find a place online to put full size image for people to download and view on computer. The problem is that these images need to stay online for long time and not be deleted by accident... otherwise our documentation becomes invalid.

where should we put these exports?

**Comment by mireille-raad** [comment]
@bdgcoder @fabregas1 do you guys have any suggestions for this?

**Comment by mireille-raad** [comment]
after our discussion, we agreed that @bdgcoder will create a folder on the BIRMS server.

File path will be: https://birms.bandung.go.id/open-contracting/documentation

**Comment by bdgcoder** [comment]
Ok. Already create the path : https://birms.bandung.go.id/open-contracting/documentation

**Comment by mireille-raad** [comment]
excellent! thank you... can you please export the files from mockflow.com and upload them there?

(can you please make sure the file names don't have space... can you replace with dash instead?)

**Comment by bdgcoder** [comment]
Dear Mireille,
I just create all the document from mokeflow in one file. https://birms.bandung.go.id/open-contracting/documentation/OC-Bandung-Mockflow.pdf
If you think we must separate alll file to one file. Just tell me.. TiTAN HADiYAN  

    On Tuesday, 20 June 2017, 9:34, Mireille Raad <notifications@github.com> wrote:
 

 excellent! thank you... can you please export the files from mockflow.com and upload them there?(can you please make sure the file names don't have space... can you replace with dash instead?)—
